---
- hosts: pc,ap
  serial: 1
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    crm_datacenter: datacenter
    crm_timezone: yourtimezone
    crm_ssh_port: 22
    crm_ssh_accepted_hosts: acceptedhosts
    crm_logrotate_dir: /etc/logrotate.d/
    crm_logrotate_mariadb: mariadb
    crm_logrotate_httpd: httpd
    crm_logrotate_crm_ap: crm
    crm_logrotate_crm_pc: crm


  tasks:
  - include:
      deploy_crm_centos7_01_base.yml

  - include:
      deploy_crm_centos7_02_clone.yml

  - include:
      deploy_crm_centos7_03_permissions.yml

 - include:
      deploy_crm_centos7_04_mysql.yml
