---
- hosts: pc,ap
  serial: 1
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    crm_datacenter: datacenter
    crm_timezone: yourtimezone

  tasks:
  - include:
      deploy_crm_centos7_01_base.yml

  - include:
      deploy_crm_centos7_02_clone.yml

  - include:
      deploy_crm_centos7_03_permissions.yml

 - include:
      deploy_crm_centos7_04_mysql.yml
